### ISSUE TITLE
Error in Heat Load Index

### ISSUE THREAD

**Issue by drvinaymanohar** [jeffreyevans/GradientMetrics#3]
![issue](https://user-images.githubusercontent.com/13574790/36945826-9540f98e-1fd9-11e8-915c-8cc5f2b62567.jpg)
I cant able to run Heat Load index tool,

i have checked the parameters in python script, but still there is an error

**Comment by jeffreyevans** [comment]
Try it now, I needed to change the index for the field that Python was looking for in the output raster.

**Comment by drvinaymanohar** [comment]
Did you corrected your code?

**Comment by jeffreyevans** [comment]
Yes, please see the message from 2 days ago.
